### ISSUE TITLE
微信扫码的 scheme 貌似被限制了

### ISSUE THREAD

**Issue by ElfSundae** [paicha/url-schemes-collecting#2]
从微信外部访问 `weixin://dl/scan` 打开微信后显示“当前页面无法访问”，在微信里面直接访问是可以跳转到扫码的。
可能这个scheme被公开了，微信给屏蔽了

**Comment by paicha** [comment]
噢，确实，新版被限制了，我更新下。

**Comment by Goner** [comment]
dl/moments 貌似也不行了

**Comment by ElfSundae** [comment]
之前网上曝出的微信 scheme 其实是抓的微信 Info.plist 里配置的 3D Touch 的快捷菜单配置， 新版微信使用了动态菜单配置，没有固定的 scheme，所以全部失效了。
可以肯定的是在有 3D Touch 功能的设备上全部失效了。 

iOS 8 或者没有 3D Touch 这个功能的 iOS 9 设备上，微信没注册应用快捷菜单，所以这些 scheme 也是无效的。这点只是我推测，待实际测试，我手头现在没有iOS 8设备。
